### ISSUE TITLE
Errors (or lack of explanation?) in tutorial section 4

### ISSUE THREAD

**Issue by serosko** [bihealth/bih-cluster#33]
Hi,
I (and others) think that there is something wrong with section 4 of the first-steps tutorial ([https://bihealth.github.io/bih-cluster/first-steps/episode-4/](https://bihealth.github.io/bih-cluster/first-steps/episode-4/)):

The snakemake -j 2 parameter tells Snakemake to use 2 cores,
but the drmaa -n 8 tells Slurm to give 8 cores to the run. Why would you do that if you tell Snakemake to only use 2 cores?
The tutorial further states that the job will use a total of 40 GB.
But according to the command line mem-per-core is 1000 MB and n is set to 8.
Slurm thus would reserve 1000 MB * 8 (mem-per-core * n) = 8 GB and not 40 GB.

**Comment by holtgrewe** [comment]
@serosko thanks for the feedback, we will look into this ASAP

**Comment by holtgrewe** [comment]
Please send such questions to the helpdesk in the future.

**Comment by stolpeo** [comment]
@serosko Thanks for pointing us to that.

1. The `-j` determines how many jobs snakemake will submit to the scheduler. The cores in the drmaa snippet refer to how many cores the actual rule will get. Note that you have the possibility to do this for every rule individually. I hope htis is now more clear in the manual.

2.  Thanks, we corrected that.

**Comment by serosko** [comment]
Thank you for the clarification.
I think the main point causing the confusion was the -j beeing the maximum number of jobs (rules) executed in parallel and not the number of cores.
Just to make sure that I now interpret this correctly: 
- At most 2 rules/jobs will be executed simultaneously (-j 2).
- Each of those 2 rules gets 8 cores (-n) and 8 * 1000MB of RAM (--mem-per-cpu=1000).

**Comment by stolpeo** [comment]
Yes. If one job finishes before the other, the next job will be spawned.

Snakemake is not clear in the phrasing and my answer is based on experience. Both parameters `--cores` and `--jobs/-j` are synonymous (see below). To get a definite answer, you would need to ask the Snakemake dev team. From the Snakemake help:

```
  --cores [N], --jobs [N], -j [N]
                        Use at most N CPU cores/jobs in parallel. If N is
                        omitted or 'all', the limit is set to the number of
                        available CPU cores. (default: None)
```

**Comment by serosko** [comment]
OK, thank you.
