### ISSUE TITLE
Can I specify a set of cluster nodes?

### ISSUE THREAD

**Issue by Krannich479** [bihealth/bih-cluster#34]
Hi, 
I am compiling code in C++ using a highly CPU level optimized (SIMD vectorized) API. Therefore, my binary is not guaranteed to work on all different cluster nodes due to varying CPU architectures. Is there a way for me to restrict slurm/snakemake/drmaa to only use a set of given cluster nodes?

**Comment by holtgrewe** [comment]
That's a very good point.

I've annotated each node with its CPU architecture now.

- https://bihealth.github.io/bih-cluster/help/faq/#how-can-i-select-a-certain-cpu-architecture

Please send such questions to the helpdesk in the future.

HTH
