### ISSUE TITLE
There is no partition named 'default'

### ISSUE THREAD

**Issue by terrycojones** [bihealth/bih-cluster#46]
https://bihealth.github.io/bih-cluster/overview/job-scheduler/ describes a partition named `default`, but that does not currently exist:

```sh
$ sinfo -O PartitionName
PARTITION           
debug               
medium              
long                
critical            
highmem             
gpu                 
mpi                 
```

**Comment by stolpeo** [comment]
Hello Terry,

you are right. Currently, `debug` equals `default`. There is a small info box:
https://bihealth.github.io/bih-cluster/overview/job-scheduler/#debug

  Oliver

**Comment by holtgrewe** [comment]
Fixed with recemt job to partition routing update.
