### ISSUE TITLE
Charité VPN Zusatzantrag B - recommended or required?

### ISSUE THREAD

**Issue by messersc** [bihealth/bih-cluster#76]
Currently, the docs say that at one point that Zusatzantrag B would be recommended, but in the troubleshooting section it is listed as a requirement.

I don't understand when Zusatzantrag B would _not_ be necessary. Wouldn't it be better if everyone just got Zusatzantrag B for cluster access?

tagging @stolpeo

**Comment by sellth** [comment]
Recommended as in "not used option 2, which is access through Charite VDI".
