### ISSUE TITLE
The scratch file removal time description isn't consistent

### ISSUE THREAD

**Issue by terrycojones** [bihealth/bih-cluster#77]
https://bihealth.github.io/bih-cluster/storage/storage-locations/ has different numbers for when scratch files are deleted.

* will be automatically removed four weeks after creation.
* will be removed within 4 weeks
* will be removed 2 weeks after their creation
* data on this volume is not to be kept for longer than 2 weeks

I am happy to fix the docs, if someone tells me what the right number is.

**Comment by messersc** [comment]
Hi Terry,

someone from CUBI should comment here, but you can have a look at the code here (might be outdated by now):
https://bihealth.github.io/bih-cluster/storage/scratch-cleanup/

So 14 days since last modification and then another 14 days in THRASH, if I read that correctly.

**Comment by messersc** [comment]
> So 14 days since last modification and then another 14 days in THRASH, if I read that correctly.

That should be correct, I will update the information accordingly.
